service: selenium-lambda-project1

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900


functions:
  hello:
    handler: handler.hello
    layers:
      - ${cf:selenium-layer-project1-dev.SeleniumLayerExport}
      - ${cf:selenium-layer-project1-dev.ChromedriverLayerExport}
