service: selenium-layer-project1

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900

layers:
  selenium:
    path: selenium
    CompatibleRuntimes: [
      "python3.6"
    ]
  chromedriver:
    path: chromedriver
    description: chrome driver layer
    CompatibleRuntimes: [
      "python3.6"
    ]
resources:
  Outputs:
    SeleniumLayerExport:
        Value:
          Ref: SeleniumLambdaLayer-project1
        Export:
          Name: SeleniumLambdaLayer-project1
    ChromedriverLayerExport:
       Value:
         Ref: ChromedriverLambdaLayer-project1
       Export:
         Name: ChromedriverLambdaLayer-project1
